create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  project text not null,
  project_manager text not null,
  title text not null,
  assignee text not null,
  start_date date not null,
  end_date date not null,
  labels text[] not null default '{}',
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.tasks enable row level security;

create policy "Allow public read tasks"
on public.tasks
for select
to anon
using (true);

create policy "Allow public insert tasks"
on public.tasks
for insert
to anon
with check (true);

create policy "Allow public update tasks"
on public.tasks
for update
to anon
using (true)
with check (true);

insert into public.tasks (
  project,
  project_manager,
  title,
  assignee,
  start_date,
  end_date,
  labels,
  completed
)
values
  ('Payments Core', 'Nina Alvarez', 'Roll out production Kubernetes node pool upgrade', 'Maya Chen', '2026-04-13', '2026-04-17', '{"kubernetes","production","infra"}', false),
  ('Developer Platform', 'Owen Blake', 'Configure GitHub Actions caching for monorepo builds', 'Rohan Patel', '2026-04-14', '2026-04-18', '{"ci-cd","github-actions","performance"}', false),
  ('Customer Analytics', 'Priya D''Souza', 'Provision staging observability dashboards', 'Elena Brooks', '2026-04-11', '2026-04-15', '{"grafana","monitoring","staging"}', false),
  ('Security Operations', 'Liam Porter', 'Rotate expiring vault secrets across shared services', 'James Kim', '2026-04-16', '2026-04-21', '{"security","vault","rotation"}', false);
