-- DevOps Tracker schema
-- Use this file in Supabase SQL Editor for both fresh databases and existing ones.

-- Optional reset for an existing database
-- Uncomment and run these lines first if you want to remove all current data and start fresh.
-- truncate table public.tasks restart identity;
-- truncate table public.devops_resources restart identity;
-- truncate table public.requesters restart identity;

-- Core tables
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  project text not null,
  requester text not null,
  title text not null,
  assignee text not null,
  start_date date not null,
  end_date date not null,
  labels text[] not null default '{}',
  completed boolean not null default false,
  task_type text not null default 'task' check (task_type in ('task', 'leave')),
  leave_reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.devops_resources (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.requesters (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

-- Existing database migration
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'tasks'
      and column_name = 'project_manager'
  ) and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'tasks'
      and column_name = 'requester'
  ) then
    alter table public.tasks rename column project_manager to requester;
  end if;
end $$;

alter table public.tasks
  add column if not exists requester text;

update public.tasks
set requester = coalesce(nullif(requester, ''), 'Resource Planner')
where requester is null or requester = '';

alter table public.tasks
  alter column requester set not null;

alter table public.tasks
  add column if not exists task_type text not null default 'task';

alter table public.tasks
  add column if not exists leave_reason text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'tasks_task_type_check'
  ) then
    alter table public.tasks
      add constraint tasks_task_type_check
      check (task_type in ('task', 'leave'));
  end if;
end $$;

-- Row level security
alter table public.tasks enable row level security;
alter table public.devops_resources enable row level security;
alter table public.requesters enable row level security;

drop policy if exists "Allow public read tasks" on public.tasks;
create policy "Allow public read tasks"
on public.tasks
for select
to anon
using (true);

drop policy if exists "Allow public insert tasks" on public.tasks;
create policy "Allow public insert tasks"
on public.tasks
for insert
to anon
with check (true);

drop policy if exists "Allow public update tasks" on public.tasks;
create policy "Allow public update tasks"
on public.tasks
for update
to anon
using (true)
with check (true);

drop policy if exists "Allow public delete tasks" on public.tasks;
create policy "Allow public delete tasks"
on public.tasks
for delete
to anon
using (true);

drop policy if exists "Allow public read devops resources" on public.devops_resources;
create policy "Allow public read devops resources"
on public.devops_resources
for select
to anon
using (true);

drop policy if exists "Allow public insert devops resources" on public.devops_resources;
create policy "Allow public insert devops resources"
on public.devops_resources
for insert
to anon
with check (true);

drop policy if exists "Allow public update devops resources" on public.devops_resources;
create policy "Allow public update devops resources"
on public.devops_resources
for update
to anon
using (true)
with check (true);

drop policy if exists "Allow public delete devops resources" on public.devops_resources;
create policy "Allow public delete devops resources"
on public.devops_resources
for delete
to anon
using (true);

drop policy if exists "Allow public read requesters" on public.requesters;
create policy "Allow public read requesters"
on public.requesters
for select
to anon
using (true);

drop policy if exists "Allow public insert requesters" on public.requesters;
create policy "Allow public insert requesters"
on public.requesters
for insert
to anon
with check (true);

drop policy if exists "Allow public update requesters" on public.requesters;
create policy "Allow public update requesters"
on public.requesters
for update
to anon
using (true)
with check (true);

drop policy if exists "Allow public delete requesters" on public.requesters;
create policy "Allow public delete requesters"
on public.requesters
for delete
to anon
using (true);
