import { type DevOpsTask } from "@/lib/tasks";

export const initialTasks: DevOpsTask[] = [
  {
    id: 1,
    project: "Payments Core",
    projectManager: "Nina Alvarez",
    title: "Roll out production Kubernetes node pool upgrade",
    assignee: "Maya Chen",
    startDate: "2026-04-13",
    endDate: "2026-04-17",
    labels: ["kubernetes", "production", "infra"],
  },
  {
    id: 2,
    project: "Developer Platform",
    projectManager: "Owen Blake",
    title: "Configure GitHub Actions caching for monorepo builds",
    assignee: "Rohan Patel",
    startDate: "2026-04-14",
    endDate: "2026-04-18",
    labels: ["ci-cd", "github-actions", "performance"],
  },
  {
    id: 3,
    project: "Customer Analytics",
    projectManager: "Priya D'Souza",
    title: "Provision staging observability dashboards",
    assignee: "Elena Brooks",
    startDate: "2026-04-11",
    endDate: "2026-04-15",
    labels: ["grafana", "monitoring", "staging"],
  },
  {
    id: 4,
    project: "Security Operations",
    projectManager: "Liam Porter",
    title: "Rotate expiring vault secrets across shared services",
    assignee: "James Kim",
    startDate: "2026-04-16",
    endDate: "2026-04-21",
    labels: ["security", "vault", "rotation"],
  },
  {
    id: 5,
    project: "Mobile Backend",
    projectManager: "Ava Singh",
    title: "Finalize blue-green deployment runbook for API cluster",
    assignee: "Maya Chen",
    startDate: "2026-04-18",
    endDate: "2026-04-22",
    labels: ["deployment", "runbook", "api"],
  },
  {
    id: 6,
    project: "Retail Launch",
    projectManager: "Marcus Lee",
    title: "Backfill Terraform modules for regional edge services",
    assignee: "Rohan Patel",
    startDate: "2026-04-10",
    endDate: "2026-04-14",
    labels: ["terraform", "edge", "networking"],
  },
  {
    id: 7,
    project: "Data Warehouse",
    projectManager: "Sofia Grant",
    title: "Tune Airflow worker autoscaling thresholds",
    assignee: "Elena Brooks",
    startDate: "2026-04-15",
    endDate: "2026-04-19",
    labels: ["airflow", "autoscaling", "ops"],
  },
  {
    id: 8,
    project: "Identity Stack",
    projectManager: "Ethan Cole",
    title: "Validate disaster recovery drill for SSO services",
    assignee: "James Kim",
    startDate: "2026-04-12",
    endDate: "2026-04-16",
    labels: ["dr", "sso", "compliance"],
  },
];
